# Generated by Django 3.0.5 on 2020-05-03 11:56

import DRapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=30)),
                ('patient_age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'apos'), ('A-', 'aneg'), ('B+', 'bpos'), ('B-', 'bneg'), ('O+', 'opos'), ('O-', 'oneg'), ('AB+', 'abpos'), ('AB-', 'abneg')], max_length=3)),
                ('patient_photo', models.ImageField(default=None, upload_to=DRapp.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='DiabeticRetinopathy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_retina_photo', models.ImageField(default=None, upload_to=DRapp.models.get_upload_path_other_two)),
                ('right_retina_photo', models.ImageField(default=None, upload_to=DRapp.models.get_upload_path_other_two)),
                ('left_predicted_stage', models.CharField(max_length=10)),
                ('right_predicted_stage', models.CharField(max_length=10)),
                ('left_confirmation', models.CharField(max_length=5)),
                ('right_confirmation', models.CharField(max_length=5)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='DiabeticHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetic_type', models.CharField(choices=[('TYPE1', 'TYPE1'), ('TYPE2', 'TYPE2')], max_length=6)),
                ('sugar_Fasting_value', models.IntegerField()),
                ('sugar_Non_fasting_value', models.IntegerField()),
                ('time_duration', models.IntegerField()),
                ('diab_report', models.FileField(default=None, upload_to=DRapp.models.get_upload_path_other_two)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRapp.Patient')),
            ],
        ),
    ]
