# Generated by Django 3.0.5 on 2020-08-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabeticretinopathy',
            name='left_confirmation',
        ),
        migrations.RemoveField(
            model_name='diabeticretinopathy',
            name='right_confirmation',
        ),
        migrations.AlterField(
            model_name='diabeticretinopathy',
            name='left_predicted_stage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='diabeticretinopathy',
            name='right_predicted_stage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
